[package]
name = "litehook"
description = "Lightweight social media monitoring tool built with Rust"
version = "3.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls", "macros", "json"] }
tdlib-rs = { version = "1.3.0", features = ["download-tdlib"] }
tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.13", features = ["json", "socks"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing-subscriber = { version = "0.3.22", features = ["chrono"] }
tower-http = { version = "0.6.8", features = ["cors", "fs"] }
uuid = { version = "1.22.0", features = ["v4"] }
html-to-markdown-rs = "2"
axum = "0.8.8"
inventory = "0.3.22"
rust-embed = "8.11"
axum-embed = "0.1"
schemars = "0.8"
rand = "0.10.0"
url = "2.5.8"
serde_json = "1.0.149"
tokio-util = "0.7"
scraper = "0.25.0"
async-trait = "0.1.89"
anyhow = "1.0"
tracing = "0.1.44"
dotenvy = "0.15.7"
envy = "0.4.2"
