services:
  litehook:
    build: .
    container_name: litehook-dev
    ports:
      - "4101:4101"
    environment:
         - WEBHOOK_SECRET=put_something_random_here
    volumes:
      - ./data:/data:rw
    restart: unless-stopped
