services:
  litehook:
    image: kitfc/litehook:latest
    container_name: litehook
    ports:
      # Or set your own port that you specified in PORT
      - "4101:4101"
    volumes:
      - ./data:/data:rw
    env_file:
      - .env
    restart: unless-stopped
